import createClient from "openapi-fetch";
import type { paths } from "$lib/types/matriarch"; // generated by openapi-typescript
import { PUBLIC_MATRIARCH_API_URL } from "$env/static/public";


export const MATRIARCH_CLIENT = createClient<paths>({ baseUrl: PUBLIC_MATRIARCH_API_URL });
